using System;
using System.Threading.Tasks;
using Gawela.RackConfig.Models;
using Gawela.RackConfig.Settings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.DependencyInjection;
using Smartstore.ComponentModel;
using Smartstore.Core.Configuration;
using Smartstore.Core.Data;
using Smartstore.Core.Seo;
using Smartstore.Core.Widgets;
using Smartstore.Engine;
using Smartstore.Engine.Builders;
using Smartstore.Engine.Modularity;
using Smartstore.Http;
using Smartstore.Web.Components;
using Smartstore.Web.Controllers;
using Smartstore.Web.Modelling;
using Smartstore.Web.Modelling.Settings;
using Smartstore.Web.Models.Catalog;

namespace Gawela.RackConfig.Settings { public class RackConfigSettings : ISettings { public bool Enabled { get; set; } = true; public int CategoryId { get; set; } public int MaxPalletWeight { get; set; } = 1000; public int DefaultDepth { get; set; } = 1100; public int MaxVariants { get; set; } = 2; public int MinLevelsLow { get; set; } = 2; public int MinLevelsHigh { get; set; } = 3; public int Spanplatte1825Id { get; set; } public int Spanplatte2700Id { get; set; } public int Spanplatte3600Id { get; set; } public int Gitterrost1825Id { get; set; } public int Gitterrost2700Id { get; set; } public int Gitterrost3600Id { get; set; } public int Stahlpanel1825Id { get; set; } public int Stahlpanel2700Id { get; set; } public int Stahlpanel3600Id { get; set; } public int Drahtgitter1825Id { get; set; } public int Drahtgitter2700Id { get; set; } public int Drahtgitter3600Id { get; set; } public int Durchschub1825Id { get; set; } public int Durchschub2700Id { get; set; } public int Durchschub3600Id { get; set; } public int EckRammschutzId { get; set; } public int MittelRammschutz76Id { get; set; } public int MittelRammschutz100Id { get; set; } } }
namespace Gawela.RackConfig.Models { public class ConfigurationModel : ModelBase { public bool Enabled { get; set; } public int CategoryId { get; set; } public int MaxPalletWeight { get; set; } public int DefaultDepth { get; set; } public int MaxVariants { get; set; } public int MinLevelsLow { get; set; } public int MinLevelsHigh { get; set; } public int Spanplatte1825Id { get; set; } public int Spanplatte2700Id { get; set; } public int Spanplatte3600Id { get; set; } public int Gitterrost1825Id { get; set; } public int Gitterrost2700Id { get; set; } public int Gitterrost3600Id { get; set; } public int Stahlpanel1825Id { get; set; } public int Stahlpanel2700Id { get; set; } public int Stahlpanel3600Id { get; set; } public int Drahtgitter1825Id { get; set; } public int Drahtgitter2700Id { get; set; } public int Drahtgitter3600Id { get; set; } public int Durchschub1825Id { get; set; } public int Durchschub2700Id { get; set; } public int Durchschub3600Id { get; set; } public int EckRammschutzId { get; set; } public int MittelRammschutz76Id { get; set; } public int MittelRammschutz100Id { get; set; } public string[] Selected(int id) => id > 0 ? new[] { id.ToString() } : Array.Empty<string>(); } }
namespace Gawela.RackConfig { internal class Module : ModuleBase, IConfigurable { public RouteInfo GetConfigurationRoute() => new("Configure", "RackConfigAdmin", new { area = "Admin" }); public override async Task InstallAsync(ModuleInstallationContext context) { await TrySaveSettingsAsync<RackConfigSettings>(); await base.InstallAsync(context); } public override async Task UninstallAsync() { await DeleteSettingsAsync<RackConfigSettings>(); await base.UninstallAsync(); } } internal class Startup : StarterBase { public override void ConfigureServices(IServiceCollection services, IApplicationContext appContext) { services.AddScoped<Filters.RackCategoryFilter>(); services.Configure<MvcOptions>(options => options.Filters.AddService<Filters.RackCategoryFilter>()); } } }
namespace Gawela.RackConfig.Controllers { [Area("Admin")][Route("Admin/RackConfig/{action=Configure}")] public class RackConfigAdminController : AdminController { [LoadSetting] public IActionResult Configure(RackConfigSettings settings) => View(MiniMapper.Map<RackConfigSettings, ConfigurationModel>(settings)); [HttpPost, SaveSetting, ValidateAntiForgeryToken] public IActionResult Configure(ConfigurationModel model, RackConfigSettings settings) { if (model.CategoryId <= 0) ModelState.AddModelError(nameof(model.CategoryId), "Bitte eine Warengruppe auswählen."); if (model.MaxPalletWeight <= 0) ModelState.AddModelError(nameof(model.MaxPalletWeight), "Die Traglast muss grösser als 0 sein."); if (model.MaxVariants < 1 || model.MaxVariants > 4) ModelState.AddModelError(nameof(model.MaxVariants), "Die Anzahl Varianten muss zwischen 1 und 4 liegen."); if (model.MinLevelsLow < 1 || model.MinLevelsHigh < model.MinLevelsLow) ModelState.AddModelError(nameof(model.MinLevelsHigh), "Die Mindestanzahl Ebenen ist ungültig."); if (!ModelState.IsValid) return View(model); ModelState.Clear(); MiniMapper.Map(model, settings); NotifySuccess("Palettenregal-Konfigurator gespeichert."); return RedirectToAction(nameof(Configure)); } } [Route("PalletRackX/{action=Config}")] public class PalletRackXController : PublicController { private readonly SmartDbContext _db; private readonly RackConfigSettings _settings; public PalletRackXController(SmartDbContext db, RackConfigSettings settings) { _db = db; _settings = settings; } public IActionResult Config() => View(_settings); [HttpGet] public async Task<IActionResult> ProductPage(int id) { if (id <= 0) return NotFound(); var product = await _db.Products.FindByIdAsync(id); if (product == null || product.Deleted) return NotFound(); return RedirectToRoute("Product", new { SeName = await product.GetActiveSlugAsync() }); } } }
namespace Gawela.RackConfig.Filters { public class RackCategoryFilter : IAsyncResultFilter { private readonly RackConfigSettings _settings; private readonly IWidgetProvider _widgetProvider; public RackCategoryFilter(RackConfigSettings settings, IWidgetProvider widgetProvider) { _settings = settings; _widgetProvider = widgetProvider; } public async Task OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next) { if (_settings.Enabled && context.Result is ViewResult viewResult && viewResult.Model is CategoryModel category) { var configured = _settings.CategoryId > 0 && category.Id == _settings.CategoryId; var legacy = _settings.CategoryId <= 0 && context.HttpContext.Request.Path.Value?.Contains("palettenregale-schnell-ab-lager-lieferbar-3", StringComparison.OrdinalIgnoreCase) == true; if (configured || legacy) _widgetProvider.RegisterWidget("categorydetails_top", new ComponentWidget<Gawela.RackConfig.Components.RackConfiguratorViewComponent> { Key = "Gawela.RackConfig" }); } await next(); } } }
namespace Gawela.RackConfig.Components { public class RackConfiguratorViewComponent : SmartViewComponent { private readonly RackConfigSettings _settings; public RackConfiguratorViewComponent(RackConfigSettings settings) { _settings = settings; } public IViewComponentResult Invoke(object model) { if (!_settings.Enabled || model is not CategoryModel category) return Empty(); if (_settings.CategoryId > 0 && category.Id != _settings.CategoryId) return Empty(); return View(_settings); } } }
